export const languages = [
    { "language": "Afrikaans", "code": "af" },
    { "language": "Arabic", "code": "ar" },
    { "language": "Bengali", "code": "bn" },
    { "language": "Bulgarian", "code": "bg" },
    { "language": "Chinese (Simplified)", "code": "zh-CN" },
    { "language": "Chinese (Traditional)", "code": "zh-TW" },
    { "language": "Czech", "code": "cs" },
    { "language": "Danish", "code": "da" },
    { "language": "Dutch", "code": "nl" },
    { "language": "English", "code": "en" },
    { "language": "Filipino", "code": "tl" },
    { "language": "Finnish", "code": "fi" },
    { "language": "French", "code": "fr" },
    { "language": "German", "code": "de" },
    { "language": "Greek", "code": "el" },
    { "language": "Gujarati", "code": "gu" },
    { "language": "Hebrew", "code": "iw" },
    { "language": "Hindi", "code": "hi" },
    { "language": "Hungarian", "code": "hu" },
    { "language": "Indonesian", "code": "id" },
    { "language": "Italian", "code": "it" },
    { "language": "Japanese", "code": "ja" },
    { "language": "Kannada", "code": "kn" },
    { "language": "Korean", "code": "ko" },
    { "language": "Malay", "code": "ms" },
    { "language": "Marathi", "code": "mr" },
    { "language": "Nepali", "code": "ne" },
    { "language": "Portuguese", "code": "pt" },
    { "language": "Punjabi", "code": "pa" },
    { "language": "Russian", "code": "ru" },
    { "language": "Spanish", "code": "es" },
    { "language": "Swedish", "code": "sv" },
    { "language": "Tamil", "code": "ta" },
    { "language": "Telugu", "code": "te" },
    { "language": "Thai", "code": "th" },
    { "language": "Turkish", "code": "tr" },
    { "language": "Ukrainian", "code": "uk" },
    { "language": "Urdu", "code": "ur" },
    { "language": "Vietnamese", "code": "vi" }
  ]
  